/* Dades de La Brúixola IA — revisades el 7 d'agost de 2026.
   Cada ferramenta: id de categoria, nom, adreça, descripció i, si cal, un avís.
   Els avisos són el que fa útil el directori: diuen què ha canviat i què cal
   saber abans de recomanar-la a l'aula. */
window.BRUIXOLA = {
  revisio: "2026-08-07",
  categories: [
    {id:"estrella", ca:"Ferramenta estrella", es:"Herramienta estrella", en:"Standout tool", fr:"Outil vedette"},
    {id:"debat",    ca:"Debat i oratòria", es:"Debate y oratoria", en:"Debate & public speaking", fr:"Débat et art oratoire"},
    {id:"comunic",  ca:"Competència comunicativa", es:"Competencia comunicativa", en:"Communication skills", fr:"Compétence communicative"},
    {id:"present",  ca:"Presentacions", es:"Presentaciones", en:"Presentations", fr:"Présentations"},
    {id:"models",   ca:"Models de llenguatge", es:"Modelos de lenguaje", en:"Language models", fr:"Modèles de langage"},
    {id:"imatges",  ca:"Imatges", es:"Imágenes", en:"Images", fr:"Images"},
    {id:"video",    ca:"Text a vídeo", es:"Texto a vídeo", en:"Text to video", fr:"Texte en vidéo"},
    {id:"audio",    ca:"Àudio", es:"Audio", en:"Audio", fr:"Audio"},
    {id:"musica",   ca:"Música", es:"Música", en:"Music", fr:"Musique"},
    {id:"artefac",  ca:"Artefactes", es:"Artefactos", en:"Build with AI", fr:"Artefacts"},
    {id:"pensa",    ca:"Pensament computacional", es:"Pensamiento computacional", en:"Computational thinking", fr:"Pensée computationnelle"},
    {id:"docent",   ca:"Assistent docent", es:"Asistente docente", en:"Teaching assistant", fr:"Assistant enseignant"},
    {id:"recerca",  ca:"Recerca", es:"Investigación", en:"Research", fr:"Recherche"},
    {id:"product",  ca:"Productivitat", es:"Productividad", en:"Productivity", fr:"Productivité"},
    {id:"agents",   ca:"Agents", es:"Agentes", en:"Agents", fr:"Agents"}
  ],
  ferramentes: [
    {c:"debat", n:"Portal de Debat i Oratòria", u:"https://sites.google.com/fundacionflors.es/debat-i-oratoria/p%C3%A0gina-principal", propi:true,
     d:"El meu repositori personal de recursos: guies, materials i estratègies per a treballar l'oratòria a l'aula."},

    {c:"estrella", n:"Gemini Notebook", alies:"NotebookLM", u:"https://notebooklm.google.com", estrella:true,
     d:"Genera pòdcasts, infografies i resums intel·ligents des dels teus documents.",
     avis:"Google el va rebatejar de NotebookLM a Gemini Notebook el juliol de 2026. Mateix producte i mateixa adreça."},

    {c:"present", n:"Gamma", u:"https://gamma.app/",
     d:"Crea presentacions, documents i pàgines web atractives a partir de text en pocs segons."},
    {c:"present", n:"Napkin AI", u:"https://napkin.ai",
     d:"Transforma text en visuals, esquemes i diagrames per a potenciar les teues presentacions."},

    {c:"debat", n:"Debate Devil", u:"https://www.debate-devil.com/en",
     d:"Entrena l'oratòria i el pensament crític amb una IA que et porta la contrària de forma mordaç.",
     avis:"Sense senyals d'activitat recent. Comprova que responga abans d'usar-la en classe."},
    {c:"debat", n:"Kialo Edu", alies:"Kialo AI", u:"https://www.kialo-edu.com",
     d:"Plataforma per a estructurar debats complexos i visualitzar la jerarquia d'arguments.",
     avis:"El nom correcte és Kialo Edu: la plataforma és gratuïta però no anuncia funcions d'IA."},
    {c:"debat", n:"Yoodli", u:"https://yoodli.ai/",
     d:"Coach d'oratòria personalitzat que analitza el teu ritme i confiança al parlar.",
     avis:"El pla gratuït s'ha reduït a 5 sessions en total, no mensuals."},
    {c:"debat", n:"Perplexity", u:"https://www.perplexity.ai",
     d:"Investigació ràpida amb fonts citades per a fonamentar arguments."},

    {c:"comunic", n:"DeepL Write", u:"https://www.deepl.com/write",
     d:"Millora l'expressió escrita corregint gramàtica, estil i to de manera intel·ligent."},
    {c:"comunic", n:"Wordtune", u:"https://www.wordtune.com/",
     d:"Reescriu les teues frases perquè siguen més clares, professionals o persuasives.",
     avis:"AI21 Labs ha discontinuat el desenvolupament del producte. Funciona, però ja no rep manteniment."},
    {c:"comunic", n:"Superhuman", alies:"Grammarly", u:"https://www.grammarly.com",
     d:"Correcció gramatical i d'estil avançada per a una comunicació impecable en anglés.",
     avis:"L'empresa Grammarly es va rebatejar com a Superhuman l'octubre de 2025; el corrector continua igual."},

    {c:"models", n:"ChatGPT", u:"https://chatgpt.com",
     d:"El model d'OpenAI pioner en conversació, redacció i anàlisi de dades."},
    {c:"models", n:"Claude", u:"https://claude.ai",
     d:"La IA d'Anthropic, referent en ètica i seguretat amb la seua IA constitucional."},
    {c:"models", n:"Gemini", u:"https://gemini.google.com",
     d:"L'aposta multimodal de Google integrada amb tot el seu ecosistema."},
    {c:"models", n:"Microsoft Copilot", u:"https://copilot.microsoft.com/",
     d:"L'assistent de Microsoft integrat en Windows i Office."},
    {c:"models", n:"DeepSeek", u:"https://www.deepseek.com/",
     d:"Model d'alt rendiment amb capacitats sorprenents en raonament i codi.",
     avis:"Bloquejat en moltes universitats i administracions per motius de privacitat i transferència de dades."},

    {c:"imatges", n:"Recraft", alies:"Red Panda AI", u:"https://www.recraft.ai/",
     d:"Generació d'imatges amb control d'estil i tipografia, molt sòlida per a materials didàctics.",
     avis:"«Red Panda» era el nom en clau de Recraft V3 durant unes proves anònimes; l'eina real és Recraft."},
    {c:"imatges", n:"ChatGPT Images", alies:"DALL·E 3", u:"https://chatgpt.com",
     d:"Generador d'imatges d'OpenAI amb una comprensió excepcional del llenguatge.",
     avis:"DALL·E 3 es retira de ChatGPT el 30 d'agost de 2026. Descarrega les imatges guardades abans d'eixa data."},
    {c:"imatges", n:"Midjourney", u:"https://www.midjourney.com/",
     d:"El referent absolut en qualitat artística i realisme visual.",
     avis:"No té pla gratuït: des de 10 $ al mes. Pensa-t'ho abans de recomanar-la a l'alumnat."},
    {c:"imatges", n:"Adobe Firefly", u:"https://firefly.adobe.com/",
     d:"IA generativa integrada en Photoshop, ètica i segura per a l'aula.",
     avis:"El pla gratuït ja no va per crèdits mensuals sinó per generacions diàries."},
    {c:"imatges", n:"Ideogram", u:"https://ideogram.ai/",
     d:"La millor eina per a generar imatges amb tipografia llegible."},
    {c:"imatges", n:"Canva Magic", u:"https://www.canva.com/",
     d:"Eines de disseny intel·ligent integrades en Canva per a docents."},

    {c:"video", n:"HeyGen", u:"https://www.heygen.com/",
     d:"Crea avatars realistes que parlen amb la teua veu i expressió corporal."},
    {c:"video", n:"Runway", alies:"Runway Gen-3", u:"https://runwayml.com",
     d:"Generació de vídeo cinematogràfic d'alt nivell professional.",
     avis:"Gen-3 es va retirar el juliol de 2026. Els models actuals són Gen-4.5 i Gen-4 Turbo."},
    {c:"video", n:"Pika Art", u:"https://pika.art",
     d:"Anima les teues idees amb clips de vídeo curts i creatius."},
    {c:"video", n:"Fliki", u:"https://fliki.ai",
     d:"Crea vídeos per a xarxes socials a partir de guions de text."},

    {c:"audio", n:"ElevenLabs", u:"https://elevenlabs.io",
     d:"La millor tecnologia de síntesi de veu i clonació vocal."},
    {c:"audio", n:"Projecte AINA", u:"https://projecteaina.cat/",
     d:"Portal oficial per a la generació de recursos de veu en català."},
    {c:"audio", n:"AudioPen", u:"https://audiopen.ai",
     d:"Converteix notes de veu desordenades en text net i estructurat."},
    {c:"audio", n:"Dictation.io", u:"https://dictation.io",
     d:"Reconeixement de veu precís directament al navegador."},

    {c:"musica", n:"Suno AI", u:"https://suno.com",
     d:"Crea cançons completes amb lletra i música de qualsevol estil.",
     avis:"El pla gratuït queda limitat a ús no comercial i ja no dona la propietat de la cançó, sinó una llicència d'ús."},
    {c:"musica", n:"Udio", u:"https://www.udio.com",
     d:"Generació musical d'alta fidelitat amb qualitat professional.",
     avis:"Després de l'acord amb Universal Music ja no es pot descarregar l'àudio: només s'escolta dins la plataforma."},
    {c:"musica", n:"LALAL.AI", u:"https://www.lalal.ai",
     d:"Separa veus i instruments de qualsevol cançó."},

    {c:"artefac", n:"Lovable", u:"https://lovable.dev/",
     d:"Crea aplicacions web completes només descrivint-les."},
    {c:"artefac", n:"Bolt.new", u:"https://bolt.new/",
     d:"Entorn de desenvolupament per a aplicacions full-stack."},
    {c:"artefac", n:"v0", alies:"v0.dev", u:"https://v0.app/",
     d:"Genera interfícies d'usuari amb React i Tailwind ràpidament.",
     avis:"Vercel ha canviat el domini de v0.dev a v0.app."},
    {c:"artefac", n:"WebSim", u:"https://websim.com/",
     d:"Simulador d'Internet on pots crear qualsevol web amb un prompt.",
     avis:"El domini ha passat de websim.ai a websim.com."},

    {c:"pensa", n:"AutoDraw", u:"https://www.autodraw.com",
     d:"Dibuix intel·ligent que prediu traços en temps real."},
    {c:"pensa", n:"Quick, Draw!", u:"https://quickdraw.withgoogle.com",
     d:"Joc de Google per a entrenar IA mitjançant el dibuix.",
     avis:"Experiment de Google sense desenvolupament actiu. Funciona, però no el faces imprescindible."},
    {c:"pensa", n:"ML for Kids", u:"https://machinelearningforkids.co.uk",
     d:"Introducció al Machine Learning per a xiquets."},
    {c:"pensa", n:"LearningML", u:"https://www.learningml.org",
     d:"Eina didàctica per a crear models de classificació."},
    {c:"pensa", n:"CodeAI", alies:"Code.org", u:"https://code.org/",
     d:"Plataforma líder per a l'aprenentatge de programació.",
     avis:"Code.org s'ha rebatejat com a CodeAI; els comptes i el domini continuen igual. L'Hora del Codi ara és l'Hora de la IA."},
    {c:"pensa", n:"Teachable Machine", u:"https://teachablemachine.withgoogle.com/",
     d:"Crea models de reconeixement d'imatges i sons fàcilment.",
     avis:"Google el manté com a experiment, sense desenvolupament actiu."},
    {c:"pensa", n:"Scratch", u:"https://scratch.mit.edu/",
     d:"Programació per blocs per a jocs i animacions.",
     avis:"La Scratch Foundation prepara una plataforma nova, amb una interrupció breu del servici i sense data confirmada."},

    {c:"docent", n:"Brisk Teaching", u:"https://www.briskteaching.com",
     d:"Automatitza rúbriques i feedback al navegador.",
     avis:"Els comptes nous tenen 14 dies de prova premium; després, la retroacció massiva passa a ser de pagament."},
    {c:"docent", n:"Magic School", u:"https://www.magicschool.ai/",
     d:"Planificació docent integral amb IA.",
     avis:"El pla gratuït té límit mensual de generacions; les il·limitades són del pla Plus."},
    {c:"docent", n:"aiEDU", u:"https://www.aiedu.org/",
     d:"Recursos d'alfabetització en IA per a l'escola."},

    {c:"recerca", n:"ResearchRabbit", u:"https://www.researchrabbit.ai/",
     d:"Visualitza connexions entre articles acadèmics.",
     avis:"Comprada per Litmaps el 2025. Continua funcionant, però ara depén d'una altra empresa."},
    {c:"recerca", n:"Consensus", u:"https://consensus.app/",
     d:"Motor de cerca d'estudis científics basat en evidències.",
     avis:"Cerques il·limitades, però 10 anàlisis Pro i 10 preguntes «Ask Paper» al mes en el pla gratuït."},
    {c:"recerca", n:"Julius AI", u:"https://julius.ai/",
     d:"Anàlisi de dades i gràfics des de fulls de càlcul.",
     avis:"El pla gratuït ha quedat molt reduït i sense crèdits mensuals."},

    {c:"product", n:"Make", u:"https://www.make.com/",
     d:"Automatització per a connectar aplicacions sense codi.",
     avis:"La facturació ha passat d'operacions a crèdits: 1.000 crèdits al mes en el pla gratuït."},

    {c:"agents", n:"Manus", u:"https://manus.ai/",
     d:"Agent d'IA autònom per a tasques complexes.",
     avis:"Any moguts en la propietat de l'empresa: la compra per part de Meta es va donar per acabada el juny de 2026."},
    {c:"agents", n:"Atlas", u:"https://atlas.nomic.ai/",
     d:"Plataforma per a connectar dades i agents d'IA."}
  ]
};
